import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { parse as yamlParse } from "yaml";
import { codexAdapter } from "../apps/cli/src/setup/codex.js";
import { hermesAdapter } from "../apps/cli/src/setup/hermes.js";
import { openCodeAdapter } from "../apps/cli/src/setup/opencode.js";
import { piAdapter } from "../apps/cli/src/setup/pi.js";
import type { SetupCtx } from "../apps/cli/src/setup/types.js";

/**
 * Un adaptador por agente, y todos escriben en configuraciones que el dev ha hecho a mano.
 * Lo que se comprueba aquí, para los cuatro, es lo mismo: que lo ajeno sobrevive, que la
 * segunda ejecución no cambia nada, que lo que dejó la instalación antigua se sustituye en
 * vez de acumularse, y que `--remove` deja el fichero utilizable.
 */

let home: string;
let calls: string[][];

function ctxWith(over: Partial<SetupCtx> = {}): SetupCtx {
  return {
    home,
    dryRun: false,
    remove: false,
    noPlugin: false,
    log: () => {},
    detect: () => true,
    exec: (bin, args) => {
      calls.push([bin, ...args]);
      return "";
    },
    now: () => new Date("2026-09-10T12:00:00Z"),
    ...over,
  };
}

function put(rel: string, content: string): string {
  const file = join(home, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  return file;
}
const readJson = (rel: string): any => JSON.parse(readFileSync(join(home, rel), "utf8"));
const backupsIn = (rel: string): string[] => (existsSync(join(home, rel)) ? readdirSync(join(home, rel)).filter((f) => f.includes(".bak-")) : []);

beforeEach(() => {
  home = mkdtempSync(join(tmpdir(), "cortex-agents-"));
  calls = [];
});
afterEach(() => rmSync(home, { recursive: true, force: true }));

describe("opencode", () => {
  const CFG = ".config/opencode/opencode.json";
  const PLUGIN = ".config/opencode/plugins/cortex.js";

  it("declara el MCP y escribe plugin y comando sin tocar lo demás", async () => {
    put(CFG, JSON.stringify({ model: "nan/deepseek-v4-flash", mcp: { notion: { type: "remote", url: "https://x" } } }));
    await openCodeAdapter.apply(ctxWith());

    const cfg = readJson(CFG);
    expect(cfg.model).toBe("nan/deepseek-v4-flash");
    expect(cfg.mcp.notion).toEqual({ type: "remote", url: "https://x" });
    expect(cfg.mcp.cortex).toEqual({ type: "local", command: ["cortex", "mcp"], enabled: true });
    expect(readFileSync(join(home, PLUGIN), "utf8")).toContain("cortex hook-capture --platform opencode");
    expect(existsSync(join(home, ".config/opencode/command/cortex-save.md"))).toBe(true);
  });

  it("re-declara el MCP que apuntaba al repo clonado", async () => {
    put(CFG, JSON.stringify({ mcp: { cortex: { type: "local", command: ["pnpm", "-C", "/repo", "--filter", "@cortex/mcp-server", "start"] } } }));
    const report = await openCodeAdapter.apply(ctxWith());
    expect(readJson(CFG).mcp.cortex.command).toEqual(["cortex", "mcp"]);
    expect(report.changed.join(" ")).toContain("cloned repo");
  });

  it("borra el plugin duplicado de la otra carpeta (OpenCode carga las dos)", async () => {
    put(".config/opencode/plugin/cortex.js", "// Generated by cortex setup\nexport const CortexPlugin = () => {};");
    const report = await openCodeAdapter.apply(ctxWith());
    expect(existsSync(join(home, ".config/opencode/plugin/cortex.js"))).toBe(false);
    expect(existsSync(join(home, PLUGIN))).toBe(true);
    expect(report.changed.join(" ")).toContain("duplicate plugin");
  });

  it("la segunda pasada no cambia nada ni deja otra copia", async () => {
    await openCodeAdapter.apply(ctxWith());
    const antes = backupsIn(".config/opencode").length;
    const report = await openCodeAdapter.apply(ctxWith());
    expect(report.changed).toHaveLength(0);
    expect(backupsIn(".config/opencode").length).toBe(antes);
  });

  it("--remove deja el resto de la config intacto", async () => {
    put(CFG, JSON.stringify({ model: "x", mcp: { notion: { url: "https://x" } } }));
    await openCodeAdapter.apply(ctxWith());
    await openCodeAdapter.remove(ctxWith({ remove: true }));
    const cfg = readJson(CFG);
    expect(cfg.mcp.cortex).toBeUndefined();
    expect(cfg.mcp.notion).toBeDefined();
    expect(cfg.model).toBe("x");
    expect(existsSync(join(home, PLUGIN))).toBe(false);
  });
});

describe("pi", () => {
  const MCP = ".pi/agent/mcp.json";

  it("instala la extensión y declara el MCP", async () => {
    put(MCP, JSON.stringify({ mcpServers: { context7: { command: "npx", args: ["-y", "@upstash/context7-mcp"] } } }));
    await piAdapter.apply(ctxWith());

    const ext = readFileSync(join(home, ".pi/agent/extensions/cortex.ts"), "utf8");
    // El contexto se inyecta UNA vez: before_agent_start salta en cada turno.
    expect(ext).toContain("before_agent_start");
    expect(ext).toContain("injected");
    expect(ext).toContain("session_shutdown");
    expect(readJson(MCP).mcpServers.cortex).toEqual({ command: "cortex", args: ["mcp"] });
    expect(readJson(MCP).mcpServers.context7).toBeDefined();
  });

  it("avisa de que Pi necesita el adaptador de MCP", async () => {
    const report = await piAdapter.apply(ctxWith());
    expect(report.warnings.join(" ")).toContain("pi-mcp-adapter");
  });

  it("--remove quita extensión y MCP y respeta los demás", async () => {
    put(MCP, JSON.stringify({ mcpServers: { engram: { command: "engram" } } }));
    await piAdapter.apply(ctxWith());
    await piAdapter.remove(ctxWith({ remove: true }));
    expect(existsSync(join(home, ".pi/agent/extensions/cortex.ts"))).toBe(false);
    expect(readJson(MCP).mcpServers).toEqual({ engram: { command: "engram" } });
  });
});

describe("hermes", () => {
  const CFG = ".hermes/config.yaml";
  const cfg = (): any => yamlParse(readFileSync(join(home, CFG), "utf8"));

  it("añade MCP y hooks conservando el resto del YAML", async () => {
    put(CFG, "model:\n  provider: openai-codex\nplugins:\n  enabled:\n    - orca-status\n");
    await hermesAdapter.apply(ctxWith());

    const c = cfg();
    expect(c.model.provider).toBe("openai-codex");
    expect(c.plugins.enabled).toEqual(["orca-status"]);
    expect(c.mcp_servers.cortex).toEqual({ command: "cortex", args: ["mcp"], enabled: true });
    expect(c.hooks.pre_llm_call[0].command).toBe("cortex hook-context --format hermes");
    expect(c.hooks.session_end[0].command).toBe("cortex hook-capture --platform hermes");
  });

  it("sustituye el hook antiguo en vez de añadir otro", async () => {
    put(CFG, "hooks:\n  pre_llm_call:\n    - command: pnpm -C /repo --filter @cortex/core run hook:context\n");
    await hermesAdapter.apply(ctxWith());
    expect(cfg().hooks.pre_llm_call).toHaveLength(1);
    expect(cfg().hooks.pre_llm_call[0].command).toBe("cortex hook-context --format hermes");
  });

  it("un YAML roto no se toca", async () => {
    put(CFG, "esto: [no cierra\n");
    const report = await hermesAdapter.apply(ctxWith());
    expect(readFileSync(join(home, CFG), "utf8")).toBe("esto: [no cierra\n");
    expect(report.warnings.join(" ")).toContain("YAML");
  });

  it("--remove conserva los hooks ajenos", async () => {
    put(CFG, "hooks:\n  pre_llm_call:\n    - command: mi-hook-propio\n");
    await hermesAdapter.apply(ctxWith());
    await hermesAdapter.remove(ctxWith({ remove: true }));
    expect(cfg().hooks.pre_llm_call).toEqual([{ command: "mi-hook-propio" }]);
    expect(cfg().mcp_servers?.cortex).toBeUndefined();
  });
});

describe("codex", () => {
  const CFG = ".codex/config.toml";

  it("instala el MISMO plugin que Claude y registra el MCP aparte", async () => {
    const report = await codexAdapter.apply(ctxWith());
    expect(calls).toContainEqual(["codex", "plugin", "marketplace", "add", "Dinacode-Labs/cortex"]);
    expect(calls).toContainEqual(["codex", "plugin", "add", "cortex@dinacode-cortex"]);
    // El plugin no aporta MCP en Codex: hay que registrarlo con su CLI.
    expect(calls).toContainEqual(["codex", "mcp", "add", "cortex", "--", "cortex", "mcp"]);
    expect(report.warnings).toHaveLength(0);
  });

  it("limpia los bloques que escribió la instalación antigua en config.toml", async () => {
    put(
      CFG,
      [
        "[mcp_servers.cortex]",
        'command = "pnpm"',
        'args = [ "-C", "/repo", "--filter", "@cortex/mcp-server", "start" ]',
        "",
        "[mcp_servers.otro]",
        'command = "npx"',
        "",
        "[[hooks.SessionStart]]",
        "[[hooks.SessionStart.hooks]]",
        'type = "command"',
        'command = "pnpm -C /repo --filter @cortex/core run hook:context"',
        "",
        "[hooks.state]",
        "",
      ].join("\n"),
    );
    const report = await codexAdapter.apply(ctxWith());
    const toml = readFileSync(join(home, CFG), "utf8");
    expect(toml).not.toContain("@cortex/mcp-server");
    expect(toml).not.toContain("hook:context");
    // Lo que no es de Cortex se queda donde estaba.
    expect(toml).toContain("[mcp_servers.otro]");
    expect(toml).toContain("[hooks.state]");
    expect(report.changed.join(" ")).toContain("old Cortex blocks");
  });

  it("si el marketplace falla, el MCP se registra igual y se avisa", async () => {
    const ctx = ctxWith({
      exec: (bin, args) => {
        calls.push([bin, ...args]);
        if (args[0] === "plugin") throw new Error("permission denied");
        return "";
      },
    });
    const report = await codexAdapter.apply(ctx);
    expect(report.warnings.join(" ")).toContain("plugin");
    expect(calls).toContainEqual(["codex", "mcp", "add", "cortex", "--", "cortex", "mcp"]);
  });
});
