import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { parse as yamlParse } from "yaml";
import { codexAdapter } from "../apps/cli/src/setup/codex.js";
import { hermesAdapter } from "../apps/cli/src/setup/hermes.js";
import { openCodeAdapter } from "../apps/cli/src/setup/opencode.js";
import { piAdapter } from "../apps/cli/src/setup/pi.js";
import { writeText } from "../apps/cli/src/setup/fs.js";
import type { SetupCtx } from "../apps/cli/src/setup/types.js";

/**
 * One adapter per agent, and all of them write into configurations the dev made by hand. What
 * is checked here, for all four, is the same: that what belongs to others survives, that the
 * second run changes nothing, that whatever the old installation left is replaced rather than
 * accumulated, and that `--remove` leaves the file usable.
 */

let home: string;
let calls: string[][];

function ctxWith(over: Partial<SetupCtx> = {}): SetupCtx {
  return {
    home,
    dryRun: false,
    remove: false,
    noPlugin: false,
    log: () => {},
    detect: () => true,
    exec: (bin, args) => {
      calls.push([bin, ...args]);
      return "";
    },
    now: () => new Date("2026-09-10T12:00:00Z"),
    ...over,
  };
}

function put(rel: string, content: string): string {
  const file = join(home, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  return file;
}
const readJson = (rel: string): any => JSON.parse(readFileSync(join(home, rel), "utf8"));
const backupsIn = (rel: string): string[] => (existsSync(join(home, rel)) ? readdirSync(join(home, rel)).filter((f) => f.includes(".bak-")) : []);

beforeEach(() => {
  home = mkdtempSync(join(tmpdir(), "cortex-agents-"));
  calls = [];
});
afterEach(() => rmSync(home, { recursive: true, force: true }));

describe("opencode", () => {
  const CFG = ".config/opencode/opencode.json";
  const PLUGIN = ".config/opencode/plugins/cortex.js";

  it("declares the MCP and writes plugin and command without touching the rest", async () => {
    put(CFG, JSON.stringify({ model: "nan/deepseek-v4-flash", mcp: { notion: { type: "remote", url: "https://x" } } }));
    await openCodeAdapter.apply(ctxWith());

    const cfg = readJson(CFG);
    expect(cfg.model).toBe("nan/deepseek-v4-flash");
    expect(cfg.mcp.notion).toEqual({ type: "remote", url: "https://x" });
    expect(cfg.mcp.cortex).toEqual({ type: "local", command: ["cortex", "mcp"], enabled: true });
    expect(readFileSync(join(home, PLUGIN), "utf8")).toContain("cortex hook-capture --platform opencode");
    expect(existsSync(join(home, ".config/opencode/command/cortex-save.md"))).toBe(true);
  });

  it("re-declares the MCP that pointed at the cloned repo", async () => {
    put(CFG, JSON.stringify({ mcp: { cortex: { type: "local", command: ["pnpm", "-C", "/repo", "--filter", "@cortex/mcp-server", "start"] } } }));
    const report = await openCodeAdapter.apply(ctxWith());
    expect(readJson(CFG).mcp.cortex.command).toEqual(["cortex", "mcp"]);
    expect(report.changed.join(" ")).toContain("cloned repo");
  });

  it("deletes the duplicate plugin from the other folder (OpenCode loads both)", async () => {
    put(".config/opencode/plugin/cortex.js", "// Generated by cortex setup\nexport const CortexPlugin = () => {};");
    const report = await openCodeAdapter.apply(ctxWith());
    expect(existsSync(join(home, ".config/opencode/plugin/cortex.js"))).toBe(false);
    expect(existsSync(join(home, PLUGIN))).toBe(true);
    expect(report.changed.join(" ")).toContain("duplicate plugin");
  });

  it("the second pass changes nothing and leaves no second copy", async () => {
    await openCodeAdapter.apply(ctxWith());
    const antes = backupsIn(".config/opencode").length;
    const report = await openCodeAdapter.apply(ctxWith());
    expect(report.changed).toHaveLength(0);
    expect(backupsIn(".config/opencode").length).toBe(antes);
  });

  it("--remove leaves the rest of the config untouched", async () => {
    put(CFG, JSON.stringify({ model: "x", mcp: { notion: { url: "https://x" } } }));
    await openCodeAdapter.apply(ctxWith());
    await openCodeAdapter.remove(ctxWith({ remove: true }));
    const cfg = readJson(CFG);
    expect(cfg.mcp.cortex).toBeUndefined();
    expect(cfg.mcp.notion).toBeDefined();
    expect(cfg.model).toBe("x");
    expect(existsSync(join(home, PLUGIN))).toBe(false);
  });
});

describe("pi", () => {
  const MCP = ".pi/agent/mcp.json";

  it("installs the extension and declares the MCP", async () => {
    put(MCP, JSON.stringify({ mcpServers: { context7: { command: "npx", args: ["-y", "@upstash/context7-mcp"] } } }));
    await piAdapter.apply(ctxWith());

    const ext = readFileSync(join(home, ".pi/agent/extensions/cortex.ts"), "utf8");
    // The context is injected ONCE: before_agent_start fires on every turn.
    expect(ext).toContain("before_agent_start");
    expect(ext).toContain("inyectado = true");
    expect(ext).toContain("session_shutdown");
    // The child's stdin is closed: with the pipe open and silent the hook hung and Pi was
    // left with no context, silently. That is why Pi was broken.
    expect(ext).toContain("stdin?.end()");
    // The directory comes from the session, not from Pi's process.
    expect(ext).toContain("ctx?.cwd");
    // The memory tools carry the `cortex.` prefix: Pi keeps the FIRST extension that registers
    // a name and does so silently, so a bare `mem_save` would make another already-installed
    // memory's tools unreachable. gentle-pi recognises them all the same because it accepts any
    // name ending in `.mem_save` (ADR-0034).
    for (const t of ["cortex.mem_save", "cortex.mem_search", "cortex.mem_get_observation", "cortex.mem_update"]) {
      expect(ext).toContain(`name: "${t}"`);
    }
    expect(ext).not.toContain('name: "mem_save"');
    expect(readJson(MCP).mcpServers.cortex).toEqual({ command: "cortex", args: ["mcp"] });
    expect(readJson(MCP).mcpServers.context7).toBeDefined();
  });

  it("warns that Pi needs the MCP adapter", async () => {
    const report = await piAdapter.apply(ctxWith());
    expect(report.warnings.join(" ")).toContain("pi-mcp-adapter");
  });

  it("--remove takes out the extension and the MCP and respects the others", async () => {
    put(MCP, JSON.stringify({ mcpServers: { engram: { command: "engram" } } }));
    await piAdapter.apply(ctxWith());
    await piAdapter.remove(ctxWith({ remove: true }));
    expect(existsSync(join(home, ".pi/agent/extensions/cortex.ts"))).toBe(false);
    expect(readJson(MCP).mcpServers).toEqual({ engram: { command: "engram" } });
  });
});

describe("hermes", () => {
  const CFG = ".hermes/config.yaml";
  const cfg = (): any => yamlParse(readFileSync(join(home, CFG), "utf8"));

  it("adds the MCP and the hooks while keeping the rest of the YAML", async () => {
    put(CFG, "model:\n  provider: openai-codex\nplugins:\n  enabled:\n    - orca-status\n");
    await hermesAdapter.apply(ctxWith());

    const c = cfg();
    expect(c.model.provider).toBe("openai-codex");
    expect(c.plugins.enabled).toEqual(["orca-status"]);
    expect(c.mcp_servers.cortex).toEqual({ command: "cortex", args: ["mcp"], enabled: true });
    expect(c.hooks.pre_llm_call[0].command).toBe("cortex hook-context --format hermes");
    expect(c.hooks.session_end[0].command).toBe("cortex hook-capture --platform hermes");
  });

  it("replaces the old hook instead of adding another", async () => {
    put(CFG, "hooks:\n  pre_llm_call:\n    - command: pnpm -C /repo --filter @cortex/core run hook:context\n");
    await hermesAdapter.apply(ctxWith());
    expect(cfg().hooks.pre_llm_call).toHaveLength(1);
    expect(cfg().hooks.pre_llm_call[0].command).toBe("cortex hook-context --format hermes");
  });

  it("a broken YAML is left alone", async () => {
    put(CFG, "this: [never closes\n");
    const report = await hermesAdapter.apply(ctxWith());
    expect(readFileSync(join(home, CFG), "utf8")).toBe("this: [never closes\n");
    expect(report.warnings.join(" ")).toContain("YAML");
  });

  it("--remove keeps other people's hooks", async () => {
    put(CFG, "hooks:\n  pre_llm_call:\n    - command: mi-hook-propio\n");
    await hermesAdapter.apply(ctxWith());
    await hermesAdapter.remove(ctxWith({ remove: true }));
    expect(cfg().hooks.pre_llm_call).toEqual([{ command: "mi-hook-propio" }]);
    expect(cfg().mcp_servers?.cortex).toBeUndefined();
  });
});

describe("codex", () => {
  const CFG = ".codex/config.toml";

  it("installs the SAME plugin as Claude and registers the MCP separately", async () => {
    const report = await codexAdapter.apply(ctxWith());
    expect(calls).toContainEqual(["codex", "plugin", "marketplace", "add", "Dinacode-Labs/cortex"]);
    expect(calls).toContainEqual(["codex", "plugin", "add", "cortex@dinacode-cortex"]);
    // The plugin brings no MCP in Codex: it has to be registered with its CLI.
    expect(calls).toContainEqual(["codex", "mcp", "add", "cortex", "--", "cortex", "mcp"]);
    expect(report.warnings).toHaveLength(0);
  });

  it("cleans up the blocks the old installation wrote into config.toml", async () => {
    put(
      CFG,
      [
        "[mcp_servers.cortex]",
        'command = "pnpm"',
        'args = [ "-C", "/repo", "--filter", "@cortex/mcp-server", "start" ]',
        "",
        "[mcp_servers.otro]",
        'command = "npx"',
        "",
        "[[hooks.SessionStart]]",
        "[[hooks.SessionStart.hooks]]",
        'type = "command"',
        'command = "pnpm -C /repo --filter @cortex/core run hook:context"',
        "",
        "[hooks.state]",
        "",
      ].join("\n"),
    );
    const report = await codexAdapter.apply(ctxWith());
    const toml = readFileSync(join(home, CFG), "utf8");
    expect(toml).not.toContain("@cortex/mcp-server");
    expect(toml).not.toContain("hook:context");
    // Anything that is not Cortex's stays where it was.
    expect(toml).toContain("[mcp_servers.otro]");
    expect(toml).toContain("[hooks.state]");
    expect(report.changed.join(" ")).toContain("old Cortex blocks");
  });

  it("when the marketplace fails, the MCP is registered anyway and it says so", async () => {
    const ctx = ctxWith({
      exec: (bin, args) => {
        calls.push([bin, ...args]);
        if (args[0] === "plugin") throw new Error("permission denied");
        return "";
      },
    });
    const report = await codexAdapter.apply(ctx);
    expect(report.warnings.join(" ")).toContain("plugin");
    expect(calls).toContainEqual(["codex", "mcp", "add", "cortex", "--", "cortex", "mcp"]);
  });
});

/**
 * The previous installation left symlinks pointing at the cloned repo. Moving the skill and the
 * command inside the plugin left those links BROKEN, and writing through one fails with ENOENT.
 * It really happened while migrating a machine: `cortex setup --all` fell over entirely.
 */
describe("symlinks the previous installation left behind", () => {
  it("a broken link is replaced by a file, without blowing up", async () => {
    const dest = join(home, ".config/opencode/command/cortex-save.md");
    mkdirSync(dirname(dest), { recursive: true });
    symlinkSync(join(home, "repo-that-no-longer-exists/config/commands/cortex-save.md"), dest);
    expect(existsSync(dest)).toBe(false); // broken: existsSync follows the link

    await openCodeAdapter.apply(ctxWith());

    expect(lstatSync(dest).isSymbolicLink()).toBe(false);
    expect(readFileSync(dest, "utf8")).toContain("save_project_context");
  });

  it("a LIVE link is not written through either: it would write into somebody else's repo", () => {
    const repo = join(home, "otro-repo");
    mkdirSync(repo, { recursive: true });
    const original = join(repo, "cortex-save.md");
    writeFileSync(original, "the repo's original content");
    const dest = join(home, ".config/opencode/command/cortex-save.md");
    mkdirSync(dirname(dest), { recursive: true });
    symlinkSync(original, dest);

    writeText(ctxWith(), dest, "contenido nuevo");

    expect(readFileSync(original, "utf8")).toBe("the repo's original content");
    expect(readFileSync(dest, "utf8")).toBe("contenido nuevo");
    expect(lstatSync(dest).isSymbolicLink()).toBe(false);
  });
});
