import { describe, it, expect, afterAll } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { walkRepo } from "../packages/core/src/code";

/**
 * walkRepo feeds code indexing (search_project_code). It must skip both the
 * dependency/artefact dirs (IGNORE_DIRS) and the PATHS generated by frameworks (Symfony's
 * var/cache, Laravel's storage/framework...). Without this, indexing a Symfony backend's root
 * pulls in thousands of chunks of cached translations that pollute search.
 */
describe("walkRepo — ignores deps and framework caches", () => {
  const root = mkdtempSync(join(tmpdir(), "cortex-repo-"));
  afterAll(() => rmSync(root, { recursive: true, force: true }));

  const file = (rel: string, body = "<?php\nreturn ['ok' => true];\n") => {
    const p = join(root, rel);
    mkdirSync(join(p, ".."), { recursive: true });
    writeFileSync(p, body);
    return p;
  };

  file("src/Controller/PaymentController.php");
  file("app/service.ts", "export const x = 1;\n");
  file("var/cache/local/translations/catalogue.es.php");
  file("var/log/prod.log", "log line");
  file("vendor/squizlabs/php_codesniffer/fixture.php");
  file("node_modules/pkg/index.js", "module.exports = {}");

  const rels = walkRepo(root).map((f) => f.relPath.split("\\").join("/")).sort();

  it("includes the code in src/ and app/", () => {
    expect(rels).toContain("src/Controller/PaymentController.php");
    expect(rels).toContain("app/service.ts");
  });

  it("excludes var/cache, var/log, vendor and node_modules", () => {
    expect(rels.some((r) => r.startsWith("var/cache/"))).toBe(false);
    expect(rels.some((r) => r.startsWith("var/log/"))).toBe(false);
    expect(rels.some((r) => r.includes("/vendor/") || r.startsWith("vendor/"))).toBe(false);
    expect(rels.some((r) => r.includes("node_modules"))).toBe(false);
  });
});
