import { closeSync, openSync, readSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, extname, basename } from "node:path";
import { getSql, toVectorLiteral, type Sql } from "@cortex/database";
import { getEmbeddingProvider, type EmbeddingProvider } from "@cortex/embeddings";
import { findProjectIdByName } from "./projects.js";
import { rrfFuse } from "./vectors.js";
import type { Row } from "./map.js";

/** Indexación y búsqueda de código por proyecto/cliente (search_project_code). */

const IGNORE_DIRS = new Set([
  "node_modules", ".git", "dist", "build", ".next", ".turbo", "coverage",
  ".cache", "vendor", "__pycache__", ".venv", "out", ".vercel", ".expect",
  ".idea", ".vscode", "tmp",
]);

const LANG: Record<string, string> = {
  ts: "typescript", tsx: "typescript", js: "javascript", jsx: "javascript",
  mjs: "javascript", cjs: "javascript", vue: "vue", php: "php", py: "python",
  go: "go", rb: "ruby", java: "java", kt: "kotlin", rs: "rust", sql: "sql",
  sh: "shell", graphql: "graphql", gql: "graphql", prisma: "prisma",
  css: "css", scss: "scss", md: "markdown", yml: "yaml", yaml: "yaml",
};

const MAX_FILE_BYTES = 200_000;
const CHUNK_LINES = 60;
const OVERLAP = 10;
// Cap por chunk y presupuesto de caracteres por petición de embeddings, para no
// exceder el contexto del modelo (qwen3-embedding: 32768 tokens) con código denso.
const MAX_CHUNK_CHARS = 4000;
const BATCH_CHAR_BUDGET = 28_000;

function ignoredFile(name: string): boolean {
  return (
    name.endsWith(".d.ts") ||
    name.endsWith(".min.js") ||
    name.endsWith(".pb.ts") ||
    /\.(gen|generated)\.[tj]sx?$/.test(name) ||
    name.startsWith("api-schema") || // clientes OpenAPI generados (yarn update-schema)
    name === "pnpm-lock.yaml" ||
    name === "package-lock.json" ||
    name === "yarn.lock"
  );
}

const GENERATED_RE =
  /@generated|auto-?generated|automatically generated|do not edit|openapi-typescript|code generated by|this file (is|was) generated/i;

/** Heurística: ¿la cabecera del fichero indica que es generado? (lee ~2KB). */
function looksGenerated(absPath: string): boolean {
  let fd: number | undefined;
  try {
    fd = openSync(absPath, "r");
    const buf = Buffer.alloc(2048);
    const n = readSync(fd, buf, 0, 2048, 0);
    return GENERATED_RE.test(buf.toString("utf8", 0, n));
  } catch {
    return false;
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

export interface CodeFile {
  absPath: string;
  relPath: string;
  language: string;
}

/** Recorre un repo y devuelve los ficheros de código indexables. */
export function walkRepo(root: string): CodeFile[] {
  const out: CodeFile[] = [];
  const visit = (dir: string) => {
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const full = join(dir, e.name);
      if (e.isDirectory()) {
        if (!e.name.startsWith(".") && !IGNORE_DIRS.has(e.name)) visit(full);
        continue;
      }
      if (!e.isFile() || ignoredFile(e.name)) continue;
      const ext = extname(e.name).slice(1).toLowerCase();
      const language = LANG[ext];
      if (!language) continue;
      try {
        if (statSync(full).size > MAX_FILE_BYTES) continue;
      } catch {
        continue;
      }
      if (looksGenerated(full)) continue;
      out.push({ absPath: full, relPath: relative(root, full), language });
    }
  };
  visit(root);
  return out;
}

export interface CodeChunk {
  relPath: string;
  language: string;
  startLine: number;
  endLine: number;
  content: string;
}

/** Trocea un fichero en ventanas de líneas con solape; antepone la ruta. */
export function chunkFile(file: CodeFile): CodeChunk[] {
  let text: string;
  try {
    text = readFileSync(file.absPath, "utf8");
  } catch {
    return [];
  }
  const lines = text.split(/\r?\n/);
  const chunks: CodeChunk[] = [];
  const step = CHUNK_LINES - OVERLAP;
  for (let i = 0; i < lines.length; i += step) {
    const slice = lines.slice(i, i + CHUNK_LINES);
    let body = slice.join("\n");
    if (body.trim().length < 10) continue;
    if (body.length > MAX_CHUNK_CHARS) body = body.slice(0, MAX_CHUNK_CHARS); // líneas minificadas/enormes
    const startLine = i + 1;
    const endLine = Math.min(i + CHUNK_LINES, lines.length);
    chunks.push({
      relPath: file.relPath,
      language: file.language,
      startLine,
      endLine,
      content: `// ${file.relPath} (líneas ${startLine}-${endLine})\n${body}`,
    });
    if (i + CHUNK_LINES >= lines.length) break;
  }
  return chunks;
}


export interface CodeHit {
  path: string;
  startLine: number;
  endLine: number;
  language: string | null;
  content: string;
  score: number;
}

/** Búsqueda híbrida (vector + FTS) sobre el código indexado de un proyecto. */
export async function searchProjectCode(
  query: string,
  project: string,
  limit = 8,
): Promise<CodeHit[]> {
  const sql = getSql();
  const provider = getEmbeddingProvider();
  const projectId = await findProjectIdByName(sql, project);
  if (!projectId) return [];

  const pool = Math.max(limit * 4, 32);
  const vectors = await provider.embed([query]);
  const lit = toVectorLiteral(vectors[0]!);

  const vecRows = (await sql`
    SELECT id, (embedding <=> ${lit}::vector) AS distance
    FROM code_chunks
    WHERE project_id = ${projectId} AND embedding_model = ${provider.model}
    ORDER BY distance ASC LIMIT ${pool}
  `) as unknown as Row[];

  const ftsRows = (await sql`
    SELECT id, ts_rank(content_tsv, plainto_tsquery('simple', ${query})) AS rank
    FROM code_chunks
    WHERE project_id = ${projectId} AND content_tsv @@ plainto_tsquery('simple', ${query})
    ORDER BY rank DESC LIMIT ${pool}
  `) as unknown as Row[];

  // Reciprocal Rank Fusion (fusión compartida en rrfFuse). A diferencia del híbrido
  // de vectors.ts, la búsqueda de código NO normaliza el RRF: usa el coseno si lo
  // hay, o el RRF crudo.
  const ranked = rrfFuse(
    vecRows as unknown as { id: string; distance?: number | string }[],
    ftsRows as unknown as { id: string }[],
    limit,
  );
  if (ranked.length === 0) return [];
  const ids = ranked.map((s) => s.id);
  const rows = (await sql`SELECT * FROM code_chunks WHERE id IN ${sql(ids)}`) as unknown as Row[];
  const byId = new Map(rows.map((r) => [r.id as string, r]));

  return ranked
    .filter((s) => byId.has(s.id))
    .map((s) => {
      const r = byId.get(s.id)!;
      return {
        path: r.path as string,
        startLine: Number(r.start_line),
        endLine: Number(r.end_line),
        language: (r.language as string) ?? null,
        content: r.content as string,
        score: s.cosine ?? s.rrf,
      };
    });
}

export function renderCodeHits(hits: CodeHit[]): string {
  if (hits.length === 0) return "Sin resultados de código.";
  return hits
    .map(
      (h) =>
        `### ${h.path}:${h.startLine}-${h.endLine} (${(h.score).toFixed(2)})\n\`\`\`${h.language ?? ""}\n${stripHeader(h.content)}\n\`\`\``,
    )
    .join("\n\n");
}

function stripHeader(content: string): string {
  // quita la línea de cabecera "// path (líneas ...)" para mostrar el código limpio
  const nl = content.indexOf("\n");
  return nl > 0 && content.startsWith("// ") ? content.slice(nl + 1) : content;
}

/** Indexa (o reindexa) un repo local en un proyecto. Devuelve nº de chunks. */
export async function indexRepo(
  project: string,
  repoPath: string,
  opts: { repoName?: string; batchSize?: number; maxChunks?: number; onProgress?: (done: number, total: number) => void } = {},
): Promise<{ files: number; chunks: number; skippedOverCap: number }> {
  const sql = getSql();
  const provider = getEmbeddingProvider();
  const projectId = await findProjectIdByName(sql, project);
  if (!projectId) throw new Error(`Proyecto no encontrado: "${project}".`);
  const repoName = opts.repoName ?? basename(repoPath.replace(/\/$/, ""));
  const batchSize = opts.batchSize ?? 32;
  const maxChunks = opts.maxChunks ?? 8000;

  const files = walkRepo(repoPath);
  let all: CodeChunk[] = [];
  for (const f of files) all.push(...chunkFile(f));
  const skippedOverCap = Math.max(0, all.length - maxChunks);
  if (skippedOverCap > 0) all = all.slice(0, maxChunks);

  // Limpia el código previo de este repo en el proyecto (reindexado idempotente).
  await sql`DELETE FROM code_chunks WHERE project_id = ${projectId} AND repo = ${repoName}`;

  let i = 0;
  let done = 0;
  while (i < all.length) {
    // Lote acotado por nº y por presupuesto de caracteres (≈ tokens) por petición.
    const batch: CodeChunk[] = [];
    let chars = 0;
    while (i < all.length && batch.length < batchSize && (batch.length === 0 || chars + all[i]!.content.length <= BATCH_CHAR_BUDGET)) {
      chars += all[i]!.content.length;
      batch.push(all[i]!);
      i++;
    }
    const vecs = await provider.embed(batch.map((c) => c.content));
    for (let j = 0; j < batch.length; j++) {
      const c = batch[j]!;
      await sql`
        INSERT INTO code_chunks (project_id, repo, path, language, start_line, end_line, content, embedding_model, dim, embedding)
        VALUES (${projectId}, ${repoName}, ${c.relPath}, ${c.language}, ${c.startLine}, ${c.endLine},
                ${c.content}, ${provider.model}, ${provider.dim}, ${toVectorLiteral(vecs[j]!)}::vector)
      `;
    }
    done += batch.length;
    opts.onProgress?.(done, all.length);
  }

  return { files: files.length, chunks: all.length, skippedOverCap };
}
