import { describe, it, expect, beforeAll, afterEach } from "vitest";
import {
  configureCore,
  createProject,
  lintProject,
  requestOtp,
  resetCore,
  saveContext,
  verifyOtp,
  type CorePorts,
  type ProjectRef,
} from "@cortex/core";
import { createApp as createWebApp } from "../../apps/web/src/app.js";

/**
 * ADR-0089: a project card shows what the last lint found, and never lints.
 *
 * The projects page linted every project the viewer could see on every view, and so did a
 * client's page for each of its repos. The lint's duplicate search compares every pair of a
 * project's vectors, so its cost grows with the square of the memos: a project of 1,800 took
 * over ten seconds on its own, and the page waited for all of them.
 */
const RID = Math.random().toString(36).slice(2, 8);
const USER = `health-${RID}@example.com`;

async function otpDe(email: string): Promise<string> {
  // The `log` sender prints `[email:log] (subject) to <email>: ...`. The code is looked for ON
  // THIS EMAIL'S LINE: several integration files intercept `console.log` at once.
  let cap = "";
  const orig = console.log;
  console.log = ((...a: unknown[]) => {
    cap += a.join(" ") + "\n";
  }) as typeof console.log;
  try {
    await requestOtp(email);
  } finally {
    console.log = orig;
  }
  const line = cap.split("\n").find((l) => l.includes(email));
  const m = line?.match(/(\d{6})/);
  if (!m) throw new Error(`the OTP for ${email} was not captured`);
  return m[1]!;
}

const lintForbidden = new Proxy(
  {},
  {
    get: () => async () => {
      throw new Error("a page painting project cards ran the lint");
    },
  },
) as CorePorts["health"];

let cookie: string;
let client: ProjectRef;
let linted: ProjectRef;

beforeAll(async () => {
  const { token } = await verifyOtp(USER, await otpDe(USER));
  cookie = `cortex_session=${token}`;
  client = await createProject(`Health Client ${RID}`, { ownerEmail: USER });
  linted = await createProject(`Health Repo ${RID}`, { ownerEmail: USER, parentSlug: client.slug! });
  await saveContext({
    content: `The invoices of ${RID} are generated by a nightly job, never on request.`,
    project: linted.name,
    type: "decision",
    createdBy: USER,
  });
  await lintProject(linted.name);
}, 120_000);

afterEach(() => resetCore());

const get = (path: string) => createWebApp().request(path, { headers: { cookie } });

function cardOf(page: string, slug: string): string {
  const start = page.indexOf(`<a class="project-card" href="/p/${slug}">`);
  if (start < 0) throw new Error(`no card for ${slug}`);
  return page.slice(start, page.indexOf("</a>", start));
}

describe("project cards read the last lint (ADR-0089)", () => {
  it("the projects page and a client's page paint their cards without linting anything", async () => {
    configureCore({ health: lintForbidden });

    for (const path of ["/", `/p/${client.slug}`]) {
      const res = await get(path);
      expect(res.status, path).toBe(200);
      const card = cardOf(await res.text(), linted.slug!);
      expect(card, path).toContain("✓ healthy");
      expect(card, path).toMatch(/title="Checked \d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC"/);
    }
    expect(cardOf(await (await get("/")).text(), client.slug!)).toContain("not checked yet");
  });

  it("a card counts the contradictions and duplicates the last lint found", async () => {
    configureCore({
      health: lintForbidden,
      healthSnapshots: {
        record: async () => {},
        latest: async () => new Map([[linted.id, { contradictions: 2, duplicates: 3, checkedAt: new Date() }]]),
      },
    });

    expect(cardOf(await (await get("/")).text(), linted.slug!)).toContain("5 to review");
  });
});
