import { raw } from "hono/html";
import type { HtmlEscapedString } from "hono/utils/html";

/** Local HTML escaping: for mdLite's internal use ONLY (the rest of the render uses html``). */
function esc(s: unknown): string {
  return String(s ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

/**
 * Lightweight, safe Markdown: it escapes ALL the input text first (esc) and only then adds its
 * own markup (bold, lists, paragraphs). Enough for the LLM agent's prose.
 *
 * It returns raw(): that is safe because the whole input goes through esc() BEFORE the tags are
 * inserted, and those tags are generated by this very code -- there is never unescaped user
 * data in the result.
 */
export function mdLite(text: string): HtmlEscapedString {
  const lines = esc(text).split(/\r?\n/);
  const out: string[] = [];
  let inList = false;
  const bold = (s: string) => s.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (line.startsWith("- ")) {
      if (!inList) { out.push("<ul>"); inList = true; }
      out.push(`<li>${bold(line.slice(2))}</li>`);
    } else {
      if (inList) { out.push("</ul>"); inList = false; }
      if (line) out.push(`<p>${bold(line)}</p>`);
    }
  }
  if (inList) out.push("</ul>");
  return raw(out.join("\n"));
}
