import { closeSync, openSync, readSync, readdirSync, readFileSync, statSync } from "node:fs";
import { extname, join, relative, sep } from "node:path";
import type { CodeFile, SourceTree } from "../domain/code.js";

/** Directories NEVER walked when indexing/ingesting a repo: dependencies and generated
 * artefacts. Shared with the document connectors (connect-docs) so no junk from
 * `vendor/`/`node_modules` is dragged into the memory. */
export const IGNORE_DIRS = new Set([
  "node_modules", ".git", "dist", "build", ".next", ".turbo", "coverage",
  ".cache", "vendor", "__pycache__", ".venv", "out", ".vercel", ".expect",
  ".idea", ".vscode", "tmp",
]);

/** Framework-generated paths (two segments, not a bare name): Symfony, Laravel and similar
 * caches/logs. Without this, indexing the root of a Symfony backend pulls in thousands of
 * chunks from `var/cache` (cached translation catalogues) that pollute code search. They are
 * compared against the path relative to the root, normalised to "/". */
const IGNORE_PATHS = new Set([
  "var/cache", "var/log", "var/logs", "var/sessions",
  "storage/framework", "storage/logs", "bootstrap/cache",
]);

const LANG: Record<string, string> = {
  ts: "typescript", tsx: "typescript", js: "javascript", jsx: "javascript",
  mjs: "javascript", cjs: "javascript", vue: "vue", php: "php", py: "python",
  go: "go", rb: "ruby", java: "java", kt: "kotlin", rs: "rust", sql: "sql",
  sh: "shell", graphql: "graphql", gql: "graphql", prisma: "prisma",
  css: "css", scss: "scss", md: "markdown", yml: "yaml", yaml: "yaml",
};

const MAX_FILE_BYTES = 200_000;

function ignoredFile(name: string): boolean {
  return (
    name.endsWith(".d.ts") ||
    name.endsWith(".min.js") ||
    name.endsWith(".pb.ts") ||
    /\.(gen|generated)\.[tj]sx?$/.test(name) ||
    name.startsWith("api-schema") ||
    name === "pnpm-lock.yaml" ||
    name === "package-lock.json" ||
    name === "yarn.lock"
  );
}

const GENERATED_RE =
  /@generated|auto-?generated|automatically generated|do not edit|openapi-typescript|code generated by|this file (is|was) generated/i;

function looksGenerated(absPath: string): boolean {
  let fd: number | undefined;
  try {
    fd = openSync(absPath, "r");
    const buf = Buffer.alloc(2048);
    const n = readSync(fd, buf, 0, 2048, 0);
    return GENERATED_RE.test(buf.toString("utf8", 0, n));
  } catch {
    return false;
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

export function walkRepo(root: string): CodeFile[] {
  const out: CodeFile[] = [];
  const visit = (dir: string) => {
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const full = join(dir, e.name);
      if (e.isDirectory()) {
        const rel = relative(root, full).split(sep).join("/");
        if (!e.name.startsWith(".") && !IGNORE_DIRS.has(e.name) && !IGNORE_PATHS.has(rel)) visit(full);
        continue;
      }
      if (!e.isFile() || ignoredFile(e.name)) continue;
      const ext = extname(e.name).slice(1).toLowerCase();
      const language = LANG[ext];
      if (!language) continue;
      try {
        if (statSync(full).size > MAX_FILE_BYTES) continue;
      } catch {
        continue;
      }
      if (looksGenerated(full)) continue;
      out.push({ absPath: full, relPath: relative(root, full), language });
    }
  };
  visit(root);
  return out;
}

export class FsSourceTree implements SourceTree {
  files(root: string): CodeFile[] {
    return walkRepo(root);
  }

  read(file: CodeFile): string | null {
    try {
      return readFileSync(file.absPath, "utf8");
    } catch {
      return null;
    }
  }
}
