import { existsSync } from "node:fs";
import { CAPTURE_DO_NOT_SAVE, captureTrigger } from "@cortex/shared";
import { homeFile, readJson, removeIfGenerated, tilde, writeIfChanged, writeJson } from "./fs.js";
import { GENERATED_MARKER, emptyReport, type AgentAdapter, type AgentStatus, type SetupCtx, type SetupReport } from "./types.js";

/**
 * Pi. Extensions are loose TypeScript files in `~/.pi/agent/extensions/`, which Pi discovers on
 * its own, and the MCP is declared in `~/.pi/agent/mcp.json`.
 *
 * Context is injected in `before_agent_start` by **chaining the system prompt**. Returning
 * `{ message }` was tried first, which Pi's documentation also allows, and it never arrived:
 * the agent started knowing nothing about the project. Chaining the system prompt is what the
 * other memory extension that works in this version of Pi uses.
 *
 * It is injected once per session, because the event fires every turn. And it **waits** for the
 * context to have arrived rather than checking a variable: nothing guarantees Pi awaits the
 * `session_start` handler before starting the first turn.
 *
 * The directory comes from `ctx.cwd`, not from `process.cwd()`: Pi's process need not be in the
 * session's repo, and getting that wrong means silently ending up with no project.
 *
 * It also registers four `cortex.mem_*` tools. The prefix is DELIBERATE: Pi resolves collisions
 * by keeping the FIRST extension that registers a name, silently, so a bare `mem_save` would
 * make unreachable the tools of anyone who already had another memory installed. With the
 * prefix both coexist. And gentle-pi recognises them all the same, because it accepts
 * `mem_save` or any name ending in `.mem_save` (ADR-0034).
 *
 * Capture comes from `session_shutdown` (and from automatic compaction, which is when a long
 * session loses its beginning). The JSONL's path arrives in `event.targetSessionFile` or in
 * `ctx.sessionManager.getSessionFile()`, which is what the hook knows how to read.
 */

/**
 * A tool's description is the only text Pi puts in front of the model on our behalf, so it is
 * where the capture protocol has to travel — in the shared wording, naming the tool Pi actually
 * has (`cortex.mem_save`, not `save_project_context`).
 */
const MEM_SAVE_DESCRIPTION = [
  "Save a piece of project knowledge (decision, constraint, convention, incident…) to Cortex, the shared project memory.",
  captureTrigger("cortex.mem_save"),
  CAPTURE_DO_NOT_SAVE,
].join(" ");

const EXT_FILE = (ctx: SetupCtx): string => homeFile(ctx, ".pi/agent/extensions/cortex.ts");
const MCP_FILE = (ctx: SetupCtx): string => homeFile(ctx, ".pi/agent/mcp.json");

const EXTENSION_TS = `// ${GENERATED_MARKER} -- do not edit this file (regenerated by \`cortex setup pi\`).
import { execFile } from "node:child_process";

interface Output { code: number; out: string; err: string }

const run = (args: string[], cwd: string): Promise<Output> =>
  new Promise((resolve) => {
    // stdin closed on purpose: the CLI reads the hook's JSON from there, and an open, silent
    // pipe left it waiting until the timeout. Here everything travels as arguments.
    const child = execFile("cortex", args, { cwd, timeout: 30000, maxBuffer: 8 * 1024 * 1024 }, (err, stdout, stderr) => {
      // A failure here left the agent with no context and said nothing. It goes to stderr,
      // which in Pi does not pollute the conversation but can still be looked at.
      if (err) console.error(\`[cortex] \${args[0]} failed: \${err.message}\`);
      resolve({ code: err ? 1 : 0, out: String(stdout ?? ""), err: String(stderr ?? "") });
    });
    child.stdin?.end();
  });

const cwdOf = (ctx: any): string => (typeof ctx?.cwd === "string" && ctx.cwd ? ctx.cwd : process.cwd());

const sessionFile = (event: any, ctx: any): string | null => {
  const f = event?.targetSessionFile ?? ctx?.sessionManager?.getSessionFile?.();
  return typeof f === "string" && f ? f : null;
};

const text = (t: string, isError = false) => ({ content: [{ type: "text" as const, text: t }], ...(isError ? { isError: true } : {}) });

/** Runs \`cortex mem ...\` and hands the agent the JSON as is, or the error in plain text. */
async function mem(args: string[], ctx: any) {
  const r = await run(["mem", ...args, "--json"], cwdOf(ctx));
  const raw = r.out.trim();
  if (r.code !== 0 || !raw) {
    let reason = r.err.trim() || "cortex mem failed";
    try { reason = JSON.parse(raw)?.error ?? reason; } catch { /* it was not JSON */ }
    return text(\`Cortex: \${reason}\`, true);
  }
  return text(raw);
}

const T = (props: Record<string, unknown>, required: string[]) => ({ type: "object", properties: props, required, additionalProperties: false });
const S = (description: string) => ({ type: "string", description });

export default function (pi: any) {
  let contexto: Promise<string | null> = Promise.resolve(null);
  let inyectado = false;

  pi.on("session_start", (_event: unknown, ctx: any) => {
    inyectado = false;
    const cwd = cwdOf(ctx);
    contexto = run(["hook-context", "--format", "text", "--cwd", cwd], cwd).then((r) => r.out.trim() || null);
    return contexto.then(() => undefined);
  });

  // before_agent_start fires on EVERY turn: the context is injected once and that is it.
  pi.on("before_agent_start", async (event: any) => {
    if (inyectado) return;
    const t = await contexto;
    if (!t) return;
    inyectado = true;
    return { systemPrompt: \`\${event?.systemPrompt ?? ""}\\n\\n\${t}\` };
  });

  const capture = async (event: any, ctx: any): Promise<void> => {
    const f = sessionFile(event, ctx);
    const cwd = cwdOf(ctx);
    if (f) await run(["hook-capture", "--platform", "pi", "--session", f, "--cwd", cwd], cwd);
  };
  pi.on("session_shutdown", async (event: any, ctx: any) => capture(event, ctx));
  pi.on("auto_compaction_start", async (event: any, ctx: any) => capture(event, ctx));

  // --- Memory as tools ----------------------------------------------------------------
  // The \`cortex.\` prefix avoids stepping on another memory extension; gentle-pi recognises
  // them all the same because it accepts any name ending in \`.mem_save\`.
  pi.registerTool({
    name: "cortex.mem_save",
    label: "Cortex: save",
    description: ${JSON.stringify(MEM_SAVE_DESCRIPTION)},
    promptSnippet: "Cortex memory: save",
    parameters: T({ content: S("What to remember, written so it still makes sense in six months"), title: S("Short, searchable title"), type: S("decision | constraint | convention | incident | risk | how_to | architecture…") }, ["content"]),
    execute: async (_id: string, p: any, _s: unknown, _u: unknown, ctx: any) =>
      mem(["save", String(p?.content ?? ""), ...(p?.title ? ["--title", String(p.title)] : []), ...(p?.type ? ["--type", String(p.type)] : [])], ctx),
  });

  pi.registerTool({
    name: "cortex.mem_search",
    label: "Cortex: search",
    description: "Search the project memory in Cortex. Returns matching entries with their ids.",
    promptSnippet: "Cortex memory: search",
    parameters: T({ query: S("Natural language or keywords"), limit: { type: "number", description: "Max results (default 10)" }, all_projects: { type: "boolean", description: "Search every project you can see, not just this one" }, type: S("Filter by entry type") }, ["query"]),
    execute: async (_id: string, p: any, _s: unknown, _u: unknown, ctx: any) =>
      mem(["search", String(p?.query ?? ""), ...(p?.limit ? ["--limit", String(p.limit)] : []), ...(p?.all_projects ? ["--all"] : []), ...(p?.type ? ["--type", String(p.type)] : [])], ctx),
  });

  pi.registerTool({
    name: "cortex.mem_get_observation",
    label: "Cortex: read entry",
    description: "Read one Cortex entry in full by its id, with where it came from.",
    promptSnippet: "Cortex memory: read entry",
    parameters: T({ id: S("Entry id, as returned by cortex.mem_search") }, ["id"]),
    execute: async (_id: string, p: any, _s: unknown, _u: unknown, ctx: any) => mem(["get", String(p?.id ?? "")], ctx),
  });

  pi.registerTool({
    name: "cortex.mem_update",
    label: "Cortex: fix entry",
    description: "Fix the title or content of a Cortex entry you got wrong. Use it to correct, not to record a change of mind: for that, save the new fact.",
    promptSnippet: "Cortex memory: fix entry",
    parameters: T({ id: S("Entry id, as returned by cortex.mem_search"), title: S("New title"), content: S("New content") }, ["id"]),
    execute: async (_id: string, p: any, _s: unknown, _u: unknown, ctx: any) =>
      mem(["update", String(p?.id ?? ""), ...(p?.title ? ["--title", String(p.title)] : []), ...(p?.content ? ["--content", String(p.content)] : [])], ctx),
  });
}
`;

interface PiMcp {
  mcpServers?: Record<string, { command?: string; args?: string[] }>;
  [k: string]: unknown;
}

export const piAdapter: AgentAdapter = {
  id: "pi",
  bin: "pi",

  async apply(ctx: SetupCtx): Promise<SetupReport> {
    const report = emptyReport();
    if (writeIfChanged(ctx, EXT_FILE(ctx), EXTENSION_TS)) report.changed.push(`extension written to ${tilde(ctx, EXT_FILE(ctx))} (context and capture)`);
    else report.skipped.push("extension already up to date");

    const file = MCP_FILE(ctx);
    const cfg = readJson<PiMcp>(file);
    if (cfg === null) {
      report.warnings.push(`${tilde(ctx, file)} is not valid JSON, so it was left alone. Add the \`cortex\` MCP by hand.`);
      return report;
    }
    const conf: PiMcp = cfg ?? {};
    conf.mcpServers ??= {};
    const want = { command: "cortex", args: ["mcp"] };
    if (JSON.stringify(conf.mcpServers.cortex) === JSON.stringify(want)) {
      report.skipped.push("MCP `cortex` already declared");
    } else {
      conf.mcpServers.cortex = want;
      writeJson(ctx, file, conf);
      report.changed.push("MCP `cortex` declared in mcp.json");
      report.warnings.push("Pi speaks MCP through `pi-mcp-adapter`. If you do not have it: pi install npm:pi-mcp-adapter");
    }
    return report;
  },

  async remove(ctx: SetupCtx): Promise<SetupReport> {
    const report = emptyReport();
    if (removeIfGenerated(ctx, EXT_FILE(ctx))) report.changed.push(`${tilde(ctx, EXT_FILE(ctx))} removed`);
    const cfg = readJson<PiMcp>(MCP_FILE(ctx));
    if (cfg?.mcpServers?.cortex) {
      delete cfg.mcpServers.cortex;
      writeJson(ctx, MCP_FILE(ctx), cfg);
      report.changed.push("MCP `cortex` removed from mcp.json");
    }
    return report;
  },

  async status(ctx: SetupCtx): Promise<AgentStatus> {
    const ext = existsSync(EXT_FILE(ctx));
    const cfg = readJson<PiMcp>(MCP_FILE(ctx));
    return {
      installed: ext,
      details: [ext ? "extension installed (context and capture)" : "extension not installed", cfg?.mcpServers?.cortex ? "MCP declared" : "MCP not declared"],
    };
  },
};
