/**
 * `cortex setup`'s contract: install Cortex's integration into EACH agent using that agent's
 * native mechanism.
 *
 * Installing the package and configuring the agents are two different things (a lesson from
 * other installers: mixing them forces a binary reinstall just to fix a config). That is why
 * `npm i -g` leaves the CLI and `cortex setup` touches the configurations, as many times as
 * needed.
 *
 * Everything goes through `SetupCtx`: `home`, running binaries and the clock all enter there,
 * so the tests run against a temporary HOME without spawning a single real process.
 */

export type AgentId = "claude-code" | "opencode" | "codex" | "hermes" | "pi";

export const AGENT_IDS: AgentId[] = ["claude-code", "opencode", "codex", "hermes", "pi"];

export interface SetupCtx {
  /** Root of the configurations (`~`, or a temporary directory in tests). */
  home: string;
  /** Writes nothing: it only reports what it would do. */
  dryRun: boolean;
  remove: boolean;
  /** Claude Code: do not use the plugin, configure hooks in settings.json instead. */
  noPlugin: boolean;
  log: (line: string) => void;
  detect: (bin: string) => boolean;
  /** Runs a binary and returns its stdout. Throws on failure. */
  exec: (bin: string, args: string[]) => string;
  now: () => Date;
}

export interface SetupReport {
  /** What was changed (or would be changed in a dry run). */
  changed: string[];
  skipped: string[];
  warnings: string[];
}

export interface AgentStatus {
  installed: boolean;
  details: string[];
}

export interface AgentAdapter {
  id: AgentId;
  bin: string;
  apply(ctx: SetupCtx): Promise<SetupReport>;
  remove(ctx: SetupCtx): Promise<SetupReport>;
  status(ctx: SetupCtx): Promise<AgentStatus>;
}

export function emptyReport(): SetupReport {
  return { changed: [], skipped: [], warnings: [] };
}

/** The marker identifying files generated by `cortex setup` (and that it may delete). */
export const GENERATED_MARKER = "Generated by cortex setup";
