/**
 * Contrato de `cortex setup`: instalar la integración de Cortex en CADA agente con su
 * mecanismo nativo.
 *
 * Instalar el paquete y configurar los agentes son dos cosas distintas (lección de otros
 * instaladores: mezclarlas obliga a reinstalar el binario para arreglar una config). Por eso
 * `npm i -g` deja el CLI y `cortex setup` toca las configuraciones, cuantas veces haga falta.
 *
 * Todo pasa por `SetupCtx`: `home`, ejecución de binarios y reloj entran por ahí, de manera
 * que los tests corren contra un HOME temporal sin lanzar ningún proceso de verdad.
 */

export type AgentId = "claude-code" | "opencode" | "codex" | "hermes" | "pi";

export const AGENT_IDS: AgentId[] = ["claude-code", "opencode", "codex", "hermes", "pi"];

export interface SetupCtx {
  /** Raíz de las configuraciones (`~`, o un temporal en tests). */
  home: string;
  /** No escribe nada: solo cuenta lo que haría. */
  dryRun: boolean;
  /** Desinstalar en vez de instalar. */
  remove: boolean;
  /** Claude Code: no usar el plugin, configurar hooks en settings.json. */
  noPlugin: boolean;
  log: (line: string) => void;
  /** ¿Está el binario del agente en el PATH? */
  detect: (bin: string) => boolean;
  /** Ejecuta un binario y devuelve su stdout. Lanza si falla. */
  exec: (bin: string, args: string[]) => string;
  now: () => Date;
}

export interface SetupReport {
  /** Lo que se ha cambiado (o se cambiaría en dry-run). */
  changed: string[];
  /** Lo que ya estaba bien. */
  skipped: string[];
  /** Lo que necesita una mano humana. */
  warnings: string[];
}

export interface AgentStatus {
  installed: boolean;
  details: string[];
}

export interface AgentAdapter {
  id: AgentId;
  /** Binario cuya presencia delata que el agente está instalado. */
  bin: string;
  apply(ctx: SetupCtx): Promise<SetupReport>;
  remove(ctx: SetupCtx): Promise<SetupReport>;
  status(ctx: SetupCtx): Promise<AgentStatus>;
}

export function emptyReport(): SetupReport {
  return { changed: [], skipped: [], warnings: [] };
}

/** Marca que identifica los ficheros que genera `cortex setup` (y que puede borrar). */
export const GENERATED_MARKER = "Generated by cortex setup";
